version: "3.9"
services:
  kotti_postgres:
    container_name: kotti_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data

  kotti_web:
    container_name: kotti_web
    build: .
    ports:
      - 8002:8000
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASS: ${DBPASS}
      POSTGRES_DBNAME: ${DBNAME}
      POSTGRES_HOST: kotti_postgres
      DJANGO_SUPERUSER_USERNAME: ${ADMIN_USER}
      DJANGO_SUPERUSER_EMAIL: ${ADMIN_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${ADMIN_PASS}
      DJANGO_KEY: ${DJANGO_KEY}
    restart: unless-stopped
    depends_on:
      - kotti_postgres
    volumes:
      - ./app/kotti:/code/kotti:rw